media:
  input: public/assets/menu
  output: /assets/menu
  categories: ["image"]

content:
  - name: menu_kuliner
    label: "Warung Raja Capybara"
    type: collection
    path: data/menu
    format: json
    view:
      fields: [image, name, description, price, category]
    fields:
      - { name: name, label: "Nama Menu", type: string, required: true }
      - { name: description, label: "Deskripsi", type: string }
      - { name: price, label: "Harga", type: string }
      - { name: image, label: "Foto Utama", type: image }
      - { name: category, label: "Kategori", type: string } # Pakai string biasa agar aman dari error map
      - { name: badge, label: "Badge (Best Seller/Promo)", type: string }
      - { name: popular, label: "Tampilkan di Populer?", type: boolean }
      
      # Mengikuti struktur 'object' yang kamu berikan tadi
      - name: metadata
        label: "Info Tambahan"
        type: object
        fields:
          - { name: created_at, label: "Tanggal Input", type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
          - { name: created_by, label: "Admin", type: string }
      
      - { name: body, label: "Detail Tambahan/Catatan", type: rich-text }